//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderik()
        {
            this.ClientOrders = new HashSet<ClientOrder>();
        }
    
        public int OrderikId { get; set; }
        public Nullable<int> Paid { get; set; }
        public string Statusik { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> DataTimik { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrder> ClientOrders { get; set; }
        public virtual Product Product { get; set; }
    }
}
