//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderik
    {
        public int OrderikId { get; set; }
        public Nullable<int> Paid { get; set; }
        public string Statusik { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> DataTimik { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
